### ISSUE TITLE
Upgrading the code to fix a lint rule error requires to run lint twice in order to remove the violations from the .lint-todo

### ISSUE THREAD

**Issue by davideferre** [scalvert/eslint-formatter-todo#479]
Updating the code to remove lint violations and then running the lint creates new entries with `remove` lines. In order to clear the lines with the fixed rule violations I need to run the lint twice. Is it an issue or something explicitly wanted?
cc: @Alonski

**Comment by Alonski** [comment]
@davideferre Thanks!
Do you think you could create a reproduction of this issue in a small app and link it here?

We can pair on this tomorrow if you need help

**Comment by davideferre** [comment]
Yep! I can share the reproduction steps with some code sample and the file content across the steps

**Comment by Alonski** [comment]
@davideferre I found out that there is an issue in our local linting setup. We can close this :)

**Comment by davideferre** [comment]
Thanks @Alonski !
